[13:51:21] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[13:51:21] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[13:51:21] [DEBUG] Initializing NativeMemory members...
[13:51:22] [DEBUG] Loading scripts from C:\Grand Theft Auto V\scripts ...
[13:51:22] [DEBUG] Loading assembly MiokoTechLoader.dll ...
[13:51:22] [INFO] Found 1 script(s) in MiokoTechLoader.dll resolved to API version 3.7.0 (script assembly version: 0.0.0.0, target API version: 3.7.0).
[13:51:22] [DEBUG] Loading assembly NAudio.dll ...
[13:51:22] [INFO] Found no compatible scripts in NAudio.dll but loaded as a library.
[13:51:22] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[13:51:22] [INFO] Found no compatible scripts in Newtonsoft.Json.dll but loaded as a library.
[13:51:22] [DEBUG] Loading assembly PedSelector.dll ...
[13:51:22] [INFO] Found 1 script(s) in PedSelector.dll resolved to API version 3.7.0 (script assembly version: 1.0.0.0, target API version: 3.7.0).
[13:51:22] [DEBUG] Loading assembly PedStatus.dll ...
[13:51:22] [INFO] Found 1 script(s) in PedStatus.dll resolved to API version 2.11.6 (script assembly version: 1.0.0.0, target API version: 2.10.14).
[13:51:22] [DEBUG] Loading assembly System.Net.Http.dll ...
[13:51:22] [INFO] Found no compatible scripts in System.Net.Http.dll but loaded as a library.
[13:51:22] [DEBUG] Loading assembly System.Web.dll ...
[13:51:22] [INFO] Found no compatible scripts in System.Web.dll but loaded as a library.
[13:51:22] [INFO] Found 1 script(s) resolved to the deprecated API version 2.x (ScriptHookVDotNet2.dll), though the script(s) are currently running. The v2 API is deprecated and no longer actively supported. It may stop being supported in the future. You could report to the authors who developed some of the scripts that are using the deprecated API, or find alternative scripts to avoid the issue. The list of script names:
[13:51:22] [INFO] PedStatus.dll
[13:51:22] [DEBUG] Instantiating script MiokoTechLoader.MiokoLoader ...
[13:51:22] [INFO] Started script MiokoTechLoader.MiokoLoader.
[13:51:22] [DEBUG] Instantiating script PedSelector.PedSelector ...
[13:51:22] [ERROR] Failed to instantiate script PedSelector.PedSelector because constructor threw an exception: System.IO.FileNotFoundException: Could not load file or assembly 'LemonUI.SHVDN3, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'LemonUI.SHVDN3, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null'
   at PedSelector.PedSelector..ctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[13:51:22] [DEBUG] Instantiating script CompanionHealth.Main ...
[13:51:22] [INFO] Started script CompanionHealth.Main.
